GET_DATA_SUCCESS_CODE = 'GET_DATA_SUCCESS_CODE'
UPDATE_DATA_SUCCESS_CODE = 'UPDATE_DATA_SUCCESS_CODE'
DELETE_DATA_SUCCESS_CODE = 'DELETE_DATA_SUCCESS_CODE'
CREATE_DATA_SUCCESS_CODE = 'CREATE_DATA_SUCCESS_CODE'

DATA_EXIST_EXPECTED_CODE = 'DATA_EXIST_EXPECTED_CODE'

INPUT_DATA_IS_INVALID = 'INPUT_DATA_IS_INVALID'

DATA_NOT_FOUND_CODE = 'DATA_NOT_FOUND_CODE'
SERVER_ERROR_CODE = 'SERVER_ERROR_CODE'
SIGN_IN_REQUIRED_CODE = 'SIGN_IN_REQUIRED_CODE'
PERMISSION_REQUIRED_CODE = 'PERMISSION_REQUIRED_CODE'
CUSTOMER_ACCOUNT_REQUIRED_CODE = 'CUSTOMER_ACCOUNT_REQUIRED_CODE'
ADMIN_ACCOUNT_REQUIRED_CODE = 'ADMIN_ACCOUNT_REQUIRED_CODE'

COMPANY_PROFILE_NOT_FOUND = 'COMPANY_PROFILE_NOT_FOUND'