from django.core.management.base import BaseCommand
from django.utils import timezone
from datetime import timedelta
import re

from django.db import transaction
from django.db import connection

from user.models import User, Payment
from doctors.models import AppWindow


class Command(BaseCommand):
    help = 'Clear test data generated by factories (safe heuristics)'

    def add_arguments(self, parser):
        parser.add_argument('--days', type=int, default=7, help='Lookback window (days) for time-based deletes (Payments)')
        parser.add_argument('--yes', action='store_true', help='Skip confirmation')

    def handle(self, *args, **options):
        days = options['days']
        skip = options['yes']

        now = timezone.now()
        since = now - timedelta(days=days)

        # Users created by our factories use email like user{n}@example.com
        user_pattern = re.compile(r'^user\d+@example\.com$')
        users_qs = User.objects.filter(email__regex=r'^user[0-9]+@example\.com$')
        users_count = users_qs.count()

        payments_qs = Payment.objects.filter(created__gte=since)
        payments_count = payments_qs.count()

        appwindows_qs = AppWindow.objects.filter(version__startswith='0.0.')
        appwindows_count = appwindows_qs.count()

        self.stdout.write('Clear test data preview:')
        self.stdout.write(f'- Users matching pattern: {users_count}')
        self.stdout.write(f'- Payments created in last {days} days: {payments_count}')
        self.stdout.write(f'- AppWindow versions starting with "0.0.": {appwindows_count}')

        if not skip:
            confirm = input('Proceed to DELETE these records? Type "yes" to confirm: ')
            if confirm.strip().lower() != 'yes':
                self.stdout.write(self.style.WARNING('Aborted by user.'))
                return

        with transaction.atomic():
            # Deleting users will cascade to related DoctorProfile and many doctor-related models
            deleted_users = users_qs.delete()
            deleted_payments = payments_qs.delete()
            deleted_app = appwindows_qs.delete()

        self.stdout.write(self.style.SUCCESS('Deletion complete. Summary:'))
        self.stdout.write(f'- Users deleted: {users_count}')
        self.stdout.write(f'- Payments deleted: {payments_count}')
        self.stdout.write(f'- AppWindow deleted: {appwindows_count}')
