# Generated by Django 2.2.9 on 2026-01-07 16:40

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('hotline', models.CharField(default='', max_length=14)),
                ('full_name', models.CharField(max_length=30)),
                ('clinic_address', models.CharField(max_length=70)),
                ('clinic_name', models.CharField(default='', max_length=100)),
                ('kind', models.CharField(choices=[('obstetrician-gynecologist', 'bác sĩ sản phụ khoa'), ('Oral maxillofacial surgeon', 'bác sĩ ngoại răng hàm mặt')], max_length=30)),
                ('is_trial', models.BooleanField(default=False)),
                ('time_end_trial', models.DateField(blank=True, null=True)),
                ('license_ultrasound', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.CharField(max_length=200)),
                ('order_desc', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('license', models.CharField(max_length=50)),
                ('vnpay_payment_url', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_period', models.CharField(help_text='(minutes)', max_length=10)),
                ('enable_voice', models.BooleanField(default=False)),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_time', to='user.DoctorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Thứ Hai'), ('sun', 'Chủ Nhật'), ('tue', 'Thứ Ba'), ('wed', 'Thứ Tư'), ('fri', 'Thứ Sáu'), ('thu', 'Thứ Năm'), ('sat', 'Thứ Bảy')], max_length=10)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('settingstime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SettingsTime')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.BooleanField(default=False)),
                ('weight', models.BooleanField(default=False)),
                ('glycemic', models.BooleanField(default=False)),
                ('ph_meter', models.BooleanField(default=False)),
                ('take_care_pregnant_baby', models.BooleanField(default=False)),
                ('point_based', models.BooleanField(default=False)),
                ('medical_ultrasonography', models.BooleanField(default=False)),
                ('medical_ultrasonography_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_ultrasonography_multi', models.BooleanField(default=False)),
                ('endoscopy', models.BooleanField(default=False)),
                ('endoscopy_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_test', models.BooleanField(default=False)),
                ('medical_test_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_test_multi', models.BooleanField(default=False)),
                ('password', models.BooleanField(default=False)),
                ('password_field', models.CharField(blank=True, max_length=20, null=True)),
                ('examination_online_cost', models.CharField(blank=True, default='', max_length=200)),
                ('medical_examination_cost', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.DoctorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_end', models.DateField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='user.DoctorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether this user should be treated as admin. Admin can manage all doctors.', verbose_name='admin PVS')),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.DoctorProfile')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
